# Generated by Django 6.0.5 on 2026-06-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_expense_product_sales_delete_setting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
