# Generated by Django 6.0.5 on 2026-06-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_delete_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pause_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
