# Generated by Django 6.0.5 on 2026-06-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_member_pause_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiry_date',
            field=models.CharField(max_length=50),
        ),
    ]
