# Generated by Django 6.0.5 on 2026-06-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_member_bmi_alter_staffs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiry_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
