# Generated by Django 6.0.5 on 2026-08-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_gymequipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='GymEquipment',
        ),
    ]
