# Generated by Django 6.0.5 on 2026-09-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_expense_branch_income_branch_sales_product_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('BRANCH_ADMIN', 'Branch Admin'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
    ]
