# Generated by Django 6.0.5 on 2026-06-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_member_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
