# Generated by Django 6.0.5 on 2026-06-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_sales_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
