# Generated by Django 6.0.5 on 2026-09-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('TENANT_ADMIN', 'Tenant Admin'), ('BRANCH_ADMIN', 'Branch Admin'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
    ]
