# Generated by Django 6.0.5 on 2026-06-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_sales_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_product',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.member'),
        ),
    ]
