# Generated by Django 6.0.5 on 2026-08-17 06:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='gif_url',
        ),
        migrations.AddField(
            model_name='exercises',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
