# Generated by Django 6.0.5 on 2026-09-17 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymequipment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gym_equipment', to='adminapp.branch'),
        ),
    ]
