# Generated by Django 6.0.5 on 2026-06-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='duration',
        ),
        migrations.AlterField(
            model_name='member',
            name='due_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.plan'),
        ),
    ]
