# Generated by Django 6.0.5 on 2026-06-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_member_duration_alter_member_due_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.DateField(max_length=100),
        ),
    ]
