# Generated by Django 6.0.5 on 2026-06-26 16:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
