# Generated by Django 6.0.5 on 2026-06-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_alter_plan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
