# Generated by Django 6.0.5 on 2026-06-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
