# Generated by Django 6.0.5 on 2026-07-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
