# Generated by Django 6.0.5 on 2026-07-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_member_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='used_pause_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
