# Generated by Django 6.0.5 on 2026-07-28 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_member_used_pause_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='payee_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='payee_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank', 'Bank Transfer')], default='cash', max_length=20),
        ),
    ]
