# Generated by Django 6.0.5 on 2026-07-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_expense_is_system_generated_expense_payee_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='payee_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='payee_phone',
            new_name='phone',
        ),
    ]
