# Generated by Django 6.0.5 on 2026-07-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_rename_payee_name_expense_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(choices=[('membership', 'Membership Fee'), ('product_sale', 'Product Sale'), ('registration', 'Registration Fee'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank', 'Bank Transfer')], default='cash', max_length=20)),
                ('date', models.DateField()),
                ('is_system_generated', models.BooleanField(default=False)),
            ],
        ),
    ]
