# Generated by Django 6.0.5 on 2026-07-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('supplements', 'Supplements'), ('protein_powder', 'Protein Powder'), ('pre_workout', 'Pre-Workout'), ('creatine', 'Creatine'), ('amino_acids', 'BCAA / EAA'), ('mass_gainer', 'Mass Gainer'), ('fat_burner', 'Fat Burner'), ('vitamins', 'Vitamins & Minerals'), ('energy_drinks', 'Energy Drinks'), ('healthy_snacks', 'Healthy Snacks'), ('gym_accessories', 'Gym Accessories'), ('lifting_gear', 'Lifting Gear'), ('apparel', 'Gym Apparel'), ('footwear', 'Footwear'), ('fitness_equipment', 'Fitness Equipment'), ('personal_care', 'Personal Care'), ('membership_items', 'Membership Items'), ('other', 'Other')], default='supplements', max_length=50),
        ),
    ]
