# Generated by Django 6.0.5 on 2026-07-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('supplements', 'Supplements'), ('equipment', 'Equipment'), ('accessories', 'Gym Accessories'), ('apparel', 'Gym Apparel'), ('nutrition', 'Nutrition & Drinks'), ('other', 'Other')], default='supplements', max_length=50),
        ),
    ]
