# Generated by Django 6.0.5 on 2026-07-29 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.member'),
        ),
    ]
