# Generated by Django 6.0.5 on 2026-07-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_income_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
