# Generated by Django 6.0.5 on 2026-07-31 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_alter_income_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('allowed_days', models.PositiveIntegerField(default=0)),
                ('paused_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pause_history', to='adminapp.member')),
            ],
        ),
    ]
