# Generated by Django 6.0.5 on 2026-08-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_memberpause'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pause_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
