# Generated by Django 6.0.5 on 2026-08-06 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_member_pause_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlanPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='diet_plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.member')),
            ],
        ),
    ]
